# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Disable macOS "Hide application" feature to prevent it from interfering with cmd+h
automatically-unhide-macos-hidden-apps = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# on-focus-changed = "move-mouse window-lazy-center"

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 18
inner.vertical =   18
outer.left =       18
outer.bottom =     18
outer.top =        18
outer.right =      18

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
# Using Hyperkey (cmd+alt+ctrl) for layout commands
cmd-alt-ctrl-slash = 'layout tiles horizontal vertical'
cmd-alt-ctrl-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
# Using arrow keys with Hyperkey (cmd+alt+ctrl)
cmd-alt-ctrl-left = 'focus left'
cmd-alt-ctrl-down = 'focus down'
cmd-alt-ctrl-up = 'focus up'
cmd-alt-ctrl-right = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
# Using arrow keys with Hyperkey+shift (cmd+alt+ctrl+shift)
cmd-alt-ctrl-shift-left = 'move left'
cmd-alt-ctrl-shift-down = 'move down'
cmd-alt-ctrl-shift-up = 'move up'
cmd-alt-ctrl-shift-right = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
# Using number keys with Hyperkey (cmd+alt+ctrl)
cmd-alt-ctrl-1 = 'workspace 1'
cmd-alt-ctrl-2 = 'workspace 2'
cmd-alt-ctrl-3 = 'workspace 3'
cmd-alt-ctrl-4 = 'workspace 4'
cmd-alt-ctrl-5 = 'workspace 5'
cmd-alt-ctrl-6 = 'workspace 6'
cmd-alt-ctrl-7 = 'workspace 7'
cmd-alt-ctrl-8 = 'workspace 8'
cmd-alt-ctrl-9 = 'workspace 9'
cmd-alt-ctrl-b = 'workspace B'
cmd-alt-ctrl-e = 'workspace E'
cmd-alt-ctrl-m = 'workspace M'
cmd-alt-ctrl-n = 'workspace N'
cmd-alt-ctrl-p = 'workspace P'
cmd-alt-ctrl-t = 'workspace T'
cmd-alt-ctrl-v = 'workspace V'
cmd-alt-ctrl-z = 'workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
# Using number keys with Hyperkey+shift (cmd+alt+ctrl+shift)
cmd-alt-ctrl-shift-1 = 'move-node-to-workspace 1'
cmd-alt-ctrl-shift-2 = 'move-node-to-workspace 2'
cmd-alt-ctrl-shift-3 = 'move-node-to-workspace 3'
cmd-alt-ctrl-shift-4 = 'move-node-to-workspace 4'
cmd-alt-ctrl-shift-5 = 'move-node-to-workspace 5'
cmd-alt-ctrl-shift-6 = 'move-node-to-workspace 6'
cmd-alt-ctrl-shift-7 = 'move-node-to-workspace 7'
cmd-alt-ctrl-shift-8 = 'move-node-to-workspace 8'
cmd-alt-ctrl-shift-9 = 'move-node-to-workspace 9'
cmd-alt-ctrl-shift-b = 'move-node-to-workspace B'
cmd-alt-ctrl-shift-e = 'move-node-to-workspace E'
cmd-alt-ctrl-shift-m = 'move-node-to-workspace M'
cmd-alt-ctrl-shift-n = 'move-node-to-workspace N'
cmd-alt-ctrl-shift-p = 'move-node-to-workspace P'
cmd-alt-ctrl-shift-t = 'move-node-to-workspace T'
cmd-alt-ctrl-shift-v = 'move-node-to-workspace V'
cmd-alt-ctrl-shift-z = 'move-node-to-workspace Z'
cmd-alt-ctrl-shift-f = 'fullscreen'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
cmd-alt-ctrl-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
cmd-alt-ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
cmd-alt-ctrl-shift-s = 'mode service'

cmd-alt-ctrl-shift-r = 'mode resize'

[mode.resize.binding]
left = 'resize width -50'
down = 'resize height +50'
up = 'resize height -50'
right = 'resize width +50'
b = 'balance-sizes'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
minus = 'resize smart -50'
equal = 'resize smart +50'

enter = 'mode main'
esc = 'mode main'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

cmd-alt-ctrl-shift-left = ['join-with left', 'mode main']
cmd-alt-ctrl-shift-down = ['join-with down', 'mode main']
cmd-alt-ctrl-shift-up = ['join-with up', 'mode main']
cmd-alt-ctrl-shift-right = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
1 = ['secondary', 'main']
2 = ['secondary', 'main']
3 = ['secondary', 'main']
4 = ['secondary', 'main']
5 = ['secondary', 'main']
6 = ['secondary', 'main']
7 = ['secondary', 'main']
8 = ['secondary', 'main']
9 = ['secondary', 'main']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.apple.SystemProfiler'
run = "move-node-to-workspace B"

